name: "Golang (release)"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Version to build'
        required: true
        default: ''
  workflow_run:
    workflows: ["Release Platform Libraries"]
    branches: ["main", "v?.*"]
    types:
      - completed

jobs:
  publish_go_tag:
    name: Tag golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: trinsic-id/set-version@v0.1
        id: setversion
        with:
          githubToken: ${{ secrets.API_GITHUB_TOKEN }}
          overrideVersion: ${{ github.event.inputs.packageVersion }}
      - name: Create tag
        run: |
          git tag "go/v${{ steps.setversion.outputs.packageVersion }}" main
          git push origin "go/v${{ steps.setversion.outputs.packageVersion }}"